apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-client
  template:
    metadata:
      labels:
        app: go-client
    spec:
      containers:
        - name: go-client
          image: your-dockerhub-user/go-client:latest
