apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: your-dockerhub-user/go-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-svc
spec:
  selector:
    app: go-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
