apiVersion: apps/v1
kind: StatefulSet
# kind: Deployment
metadata:
  name: {{ include "go-server.fullname" . }}
  labels:
    app: {{ include "go-server.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "go-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "go-server.name" . }}
    spec:
      containers:
        - name: go-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: http_proxy
              value: http://7.182.101.79:3128
            - name: https_proxy
              value: http://7.182.101.79:3128
            - name: HTTP_PROXY
              value: http://7.182.101.79:3128
            - name: HTTPS_PROXY
              value: http://7.182.101.79:3128
            - name: no_proxy
              value: localhost,127.0.0.1,.svc,.cluster.local
