apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-server.fullname" . }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ include "go-server.name" . }}
  ports:
    - port: 8081
      targetPort: {{ .Values.service.port }}
