name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: tehilathestudent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Find and Build Dockerfiles
        shell: bash
        run: |
          find . -type f -name 'Dockerfile.*' | while read dockerfile; do
            # Get image name from filename: Dockerfile.image-name -> image-name
            filename=$(basename "$dockerfile")
            image_name="${filename#Dockerfile.}"

            # Get build context as the directory containing the Dockerfile
            build_context=$(dirname "$dockerfile")

            echo "🚀 Building $image_name from $dockerfile with context $build_context"

            docker build -t "$DOCKERHUB_USER/$image_name:latest" -f "$dockerfile" "$build_context"
            docker push "$DOCKERHUB_USER/$image_name:latest"
          done
